In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("transfers.csv")

In [3]:
df

,Age,Heights,Winter_window,matches,goals,asissts,pen_goals,y_card,champions_league,europa_league,...,Transfer_year_2021,Transfer_year_2022,Transfer_year_2023,Transfer_year_2024,r_card_1,r_card_2,r_card_3,Goalkeeper,Defender,Forward
0,26,180,1,20,8,0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,1
1,23,173,0,22,2,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,27,173,1,16,1,2,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
3,24,175,0,36,7,12,3,5,0,0,...,0,0,0,0,0,0,0,0,0,0
4,25,188,1,12,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,18,174,0,8,0,0,0,2,0,0,...,0,0,0,1,0,0,0,0,1,0
2022,18,191,0,1,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,1,0
2023,28,170,0,45,15,11,0,13,0,1,...,0,0,0,1,1,0,0,0,0,1
2024,31,184,1,19,1,3,0,4,0,0,...,0,0,0,1,0,0,0,0,0,0
2025,22,171,1,2,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [4]:
q = 5
df["Age"] = pd.qcut(df["Age"], q=q)

df["Age"] = df["Age"].apply(
    lambda x: f"Age_{int(x.left)}_{int(x.right)}"
)

In [5]:
q = 4
df["Heights"] = pd.qcut(df["Heights"], q=q)

df["Heights"] = df["Heights"].apply(
    lambda x: f"Heights_{int(x.left)}_{int(x.right)}"
)

In [6]:
q = 4
df["matches"] = pd.qcut(df["matches"], q=q)

df["matches"] = df["matches"].apply(
    lambda x: f"matches_{int(x.left)}_{int(x.right)}"
)

In [7]:
q = 3
df["goals"] = pd.qcut(df["goals"], q=q)

df["goals"] = df["goals"].apply(
    lambda x: f"goals_{int(x.left)}_{int(x.right)}"
)

In [8]:
q = 3
df["asissts"] = pd.qcut(df["asissts"], q=q)

df["asissts"] = df["asissts"].apply(
    lambda x: f"asissts_{int(x.left)}_{int(x.right)}"
)

In [9]:
df["pen_goals"] = df["pen_goals"].apply(
    lambda x: "pen_goals_0" if x == 0 else "pen_goals_>0"
)

In [10]:
q = 3
df["y_card"] = pd.qcut(df["y_card"], q=q)

df["y_card"] = df["y_card"].apply(
    lambda x: f"y_card_{int(x.left)}_{int(x.right)}"
)

In [11]:
df["europa_matches"] = df["europa_matches"].apply(
    lambda x: "europa_matches_0" if x == 0 else "europa_matches_>0"
)

In [12]:
df["europa_goals"] = df["europa_goals"].apply(
    lambda x: "europa_goals_0" if x == 0 else "europa_goals_>0"
)

In [13]:
df["europa_asissts"] = df["europa_asissts"].apply(
    lambda x: "europa_asissts_0" if x == 0 else "europa_asissts_>0"
)

In [14]:
q = 2
df["nation_matches"] = pd.qcut(df["nation_matches"], q=q)

df["nation_matches"] = df["nation_matches"].apply(
    lambda x: f"nation_matches_{int(x.left)}_{int(x.right)}"
)

In [15]:
df["nation_goals"] = df["nation_goals"].apply(
    lambda x: "nation_goals_0" if x == 0 else "nation_goals_>0"
)

In [16]:
df

,Age,Heights,Winter_window,matches,goals,asissts,pen_goals,y_card,champions_league,europa_league,...,Transfer_year_2021,Transfer_year_2022,Transfer_year_2023,Transfer_year_2024,r_card_1,r_card_2,r_card_3,Goalkeeper,Defender,Forward
0,Age_25_28,Heights_178_183,1,matches_0_20,goals_5_36,asissts_0_1,pen_goals_>0,y_card_0_2,0,0,...,0,0,0,0,0,0,0,0,0,1
1,Age_21_23,Heights_159_178,0,matches_20_30,goals_1_5,asissts_1_3,pen_goals_0,y_card_0_2,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Age_25_28,Heights_159_178,1,matches_0_20,goals_0_1,asissts_1_3,pen_goals_0,y_card_0_2,1,0,...,0,0,0,0,0,0,0,0,0,0
3,Age_23_25,Heights_159_178,0,matches_30_37,goals_5_36,asissts_3_23,pen_goals_>0,y_card_2_5,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Age_23_25,Heights_183_188,1,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,Age_16_21,Heights_159_178,0,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,0,0,...,0,0,0,1,0,0,0,0,1,0
2022,Age_16_21,Heights_188_206,0,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,0,0,...,0,0,0,1,1,0,0,0,1,0
2023,Age_25_28,Heights_159_178,0,matches_37_56,goals_5_36,asissts_3_23,pen_goals_0,y_card_5_18,0,1,...,0,0,0,1,1,0,0,0,0,1
2024,Age_28_36,Heights_183_188,1,matches_0_20,goals_0_1,asissts_1_3,pen_goals_0,y_card_2_5,0,0,...,0,0,0,1,0,0,0,0,0,0
2025,Age_21_23,Heights_159_178,1,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,0,0,...,0,0,0,1,0,0,0,0,0,0

In [17]:
def collapse_binary_columns(
    df: pd.DataFrame,
    mapping: dict,
    new_col: str,
    default_value: str | None = None
):
    def get_value(row):
        active = [
            label
            for col, label in mapping.items()
            if col in row.index and row[col] == 1
        ]

        if len(active) == 1:
            return active[0]
        elif len(active) == 0:
            return default_value
        else:
            return "Multiple"   # data quality issue

    df[new_col] = df.apply(get_value, axis=1)

    # drop only columns that actually exist
    drop_cols = [c for c in mapping.keys() if c in df.columns]
    df.drop(columns=drop_cols, inplace=True)

    return df

In [18]:
POSITION_COLS = {
    "Goalkeeper": "Goalkeeper",
    "Defender": "Defender",
    "Forward": "Forward"
}

df = collapse_binary_columns(
    df,
    mapping=POSITION_COLS,
    new_col="Position",
    default_value="Midfielder"
)

In [19]:
R_CARD_COLS = {
    "r_card_1": "r_card_1",
    "r_card_2": "r_card_2",
    "r_card_3": "r_card_3"
}

df = collapse_binary_columns(
    df,
    mapping=R_CARD_COLS,
    new_col="r_card",
    default_value="r_card_0"
)

In [20]:
TRANSFER_YEAR_COLS = {
    "Transfer_year_2011": "Transfer_year_2011",
    "Transfer_year_2012": "Transfer_year_2012",
    "Transfer_year_2013": "Transfer_year_2013",
    "Transfer_year_2014": "Transfer_year_2014",
    "Transfer_year_2015": "Transfer_year_2015",
    "Transfer_year_2016": "Transfer_year_2016",
    "Transfer_year_2017": "Transfer_year_2017",
    "Transfer_year_2018": "Transfer_year_2018",
    "Transfer_year_2019": "Transfer_year_2019",
    "Transfer_year_2020": "Transfer_year_2020",
    "Transfer_year_2021": "Transfer_year_2021",
    "Transfer_year_2022": "Transfer_year_2022",
    "Transfer_year_2023": "Transfer_year_2023",
    "Transfer_year_2024": "Transfer_year_2024",
    "Transfer_year_2025": "Transfer_year_2025",
    "Transfer_year_2026": "Transfer_year_2026",
}

df = collapse_binary_columns(
    df,
    mapping=TRANSFER_YEAR_COLS,
    new_col="Transfer_year",
    default_value="Transfer_year_2010"
)

In [21]:
CONTINENT_COLS = {
    "Africa": "Africa",
    "Asia": "Asia",
    "Europe": "Europe",
    "North_America": "North_America",
    "South_America": "South_America"
}

df = collapse_binary_columns(
    df,
    mapping=CONTINENT_COLS,
    new_col="Continent",
    default_value="Oceania"
)

In [22]:
df["Transfer_window"] = df["Winter_window"].map({
    0: "Summer_window",
    1: "Winter_window"
})

# drop old binary column
df.drop(columns=["Winter_window"], inplace=True)

In [23]:
EUROPEAN_COMPETITIONS_COLS = {
    "champions_league": "champions_league",
    "europa_league": "europa_league"
}

df = collapse_binary_columns(
    df,
    mapping=EUROPEAN_COMPETITIONS_COLS,
    new_col="european_competitions",
    default_value="no_participation"
)

In [24]:
BINARY_EXPLICIT_COLS = [
    "English",
    "Homegrown",
    "From_Premier_League",
    "From_top_5_leagues",
    "From_FA_leagues",
    "From_europe_leagues",
    "From_south_america_leagues",
    "From_big_six",
    "To_Premier_League",
    "To_top_5_leagues",
    "To_FA_leagues",
    "To_europe_leagues",
    "To_south_america_leagues",
    "To_saudi_arabic_league",
    "To_big_six",
]

def binary_to_explicit_category(df, columns):
    """
    Convert binary columns (0/1) into explicit categorical variables:
    1 -> column name
    0 -> 'not_' + column name
    """
    for col in columns:
        if col not in df.columns:
            continue

        df[col] = df[col].map({
            1: col,
            0: f"not_{col}"
        })

    return df

df = binary_to_explicit_category(df, BINARY_EXPLICIT_COLS)

In [25]:
FOOT_COLS = {
    "is_right": "right",
    "is_both": "both"
}

df = collapse_binary_columns(
    df,
    mapping=FOOT_COLS,
    new_col="Foot",
    default_value="left"
)

In [26]:
df

,Age,Heights,matches,goals,asissts,pen_goals,y_card,europa_matches,europa_goals,europa_asissts,...,From_big_six,To_big_six,Homegrown,Position,r_card,Transfer_year,Continent,Transfer_window,european_competitions,Foot
0,Age_25_28,Heights_178_183,matches_0_20,goals_5_36,asissts_0_1,pen_goals_>0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,Homegrown,Forward,r_card_0,Transfer_year_2010,Europe,Winter_window,no_participation,right
1,Age_21_23,Heights_159_178,matches_20_30,goals_1_5,asissts_1_3,pen_goals_0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,From_big_six,not_To_big_six,Homegrown,Midfielder,r_card_0,Transfer_year_2010,Europe,Summer_window,no_participation,right
2,Age_25_28,Heights_159_178,matches_0_20,goals_0_1,asissts_1_3,pen_goals_0,y_card_0_2,europa_matches_>0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,not_Homegrown,Midfielder,r_card_0,Transfer_year_2010,Africa,Winter_window,champions_league,right
3,Age_23_25,Heights_159_178,matches_30_37,goals_5_36,asissts_3_23,pen_goals_>0,y_card_2_5,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,To_big_six,Homegrown,Midfielder,r_card_0,Transfer_year_2010,Europe,Summer_window,no_participation,right
4,Age_23_25,Heights_183_188,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,Homegrown,Defender,r_card_0,Transfer_year_2010,Africa,Winter_window,no_participation,right
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,Age_16_21,Heights_159_178,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,not_Homegrown,Defender,r_card_0,Transfer_year_2024,South_America,Summer_window,no_participation,right
2022,Age_16_21,Heights_188_206,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,not_Homegrown,Defender,r_card_1,Transfer_year_2024,Europe,Summer_window,no_participation,left
2023,Age_25_28,Heights_159_178,matches_37_56,goals_5_36,asissts_3_23,pen_goals_0,y_card_5_18,europa_matches_>0,europa_goals_>0,europa_asissts_>0,...,not_From_big_six,not_To_big_six,not_Homegrown,Forward,r_card_1,Transfer_year_2024,Europe,Summer_window,europa_league,right
2024,Age_28_36,Heights_183_188,matches_0_20,goals_0_1,asissts_1_3,pen_goals_0,y_card_2_5,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,not_Homegrown,Midfielder,r_card_0,Transfer_year_2024,Africa,Winter_window,no_participation,right
2025,Age_21_23,Heights_159_178,matches_0_20,goals_0_1,asissts_0_1,pen_goals_0,y_card_0_2,europa_matches_0,europa_goals_0,europa_asissts_0,...,not_From_big_six,not_To_big_six,Homegrown,Midfielder,r_card_0,Transfer_year_2024,Europe,Winter_window,no_participation,right

In [27]:
#df.to_csv("transfers_ar.csv", index=False)